<!DOCTYPE html>
<html>
    <head>
     <meta charset="utf-8">
        <title> Trombinoscope THYP 2014/2015 </title>
		<style>
			h1{
			color:#24b9ff;
			}
			#absent{
			background-color:red;
			}
		
			#present{
			background-color:green;			
			}
			
			body{
			background-color: #FFFFF0;
			}
			
			
		</style>
	</head>
	<body>

<?php
//charge le flux rss dans un objet PHP
$xml = simplexml_load_file('http://picasaweb.google.com/data/feed/base/user/107401320610499259896/albumid/6065229773950541889?alt=rss&kind=photo&authkey=Gv1sRgCNak7e60l-7VlgE&hl=fr');

echo '<h1 id = "titre" align="center">Trombinoscope THYP 2014/2015</h1>';

foreach ($xml->channel->item as $tof) {
	
	echo '<div id ="position" align="center">';	
	echo "<img src='".$tof->enclosure["url"]."' />" . "<br/>$tof->title<br/><br/>";
	echo '<form action="BoukellaRafik/exam/public/Ecrire/ecrireAbsence" method="post">';
	echo '<input type="submit" name="absent" value="Absent" id="absent" >';	
	echo '</form>';
	echo '<form action="BoukellaRafik/exam/public/Ecrire/ecrirePresence" method="post">';
	echo '<input type="submit" name="present" value="Present" id="present" >';	
	echo '</form>';
	echo '</div><br/><br/>';
}
?>

	</body>
</html>